### ISSUE TITLE
list all customers

### ISSUE THREAD

**Issue by MHSEA** [MHSEA/HotelReception#2]
The command (list all) will work with all classes such as:
list all customers
list all rooms
list all services
list all bookings

My concern is, as only the manager should have access to customer list and booking details and our app main user is customer, i think i would be good if we could implement a security or admin feature for only these two commands:

list all customers
list all bookings

I have tried in line password for listing but i will apply to all of them
This part has been commented out in the reasoner
![capture](https://cloud.githubusercontent.com/assets/12767335/11971010/d4a81712-a92d-11e5-8aac-92f80fbb2474.PNG)

Here is the example:
![reception](https://cloud.githubusercontent.com/assets/12767335/11971025/08b8643a-a92e-11e5-872d-4e8bd0280129.PNG)

**Comment by MoafaqJamal** [comment]
That's a really cool feature!!

**Comment by MHSEA** [comment]
Issue Has been resolved, i have implemented a new validation method.
Admin Password is needed for using following commands:
- List All Customers
- List All Bookings

![capture](https://cloud.githubusercontent.com/assets/12767335/12009415/bcf0db98-ac6d-11e5-86c6-6125e8abe25c.PNG)
